### ISSUE TITLE
"craftpair" text itself showing up incorrectly.

### ISSUE THREAD

**Issue by marvinmathai** [marvinmathai/craftpair#35]
Please see the atatched screesnhto.The 'craftpair' text itself is showing up differently. Some have 'C' in upper case, while, some have 'P' in the uppercase. 
All the text should be consistent across all the pages in the website.
![craftpairtext](https://cloud.githubusercontent.com/assets/11717820/8818771/1bae0822-3063-11e5-832a-454f0659d6b5.png)

**Comment by haianandu123** [comment]
Solved..!!
